import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import localFont from "next/font/local";
import "./globals.css";
import ChatPage from "../pages/ChatPage";
import LibraryPage from "../pages/LibraryPage";
import AppSidebar from "@/components/AppSidebar";
import ClientRouter from "@/components/ClientRouter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout() {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <ClientRouter>
            <AppSidebar />
            <main className="flex-1">
              <LibraryPage />
            </main>
          </ClientRouter>
        </SidebarProvider>
      </body>
    </html>
  );
}
