name: Manual Project Deploy
on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch (default: master)'
        required: false
        default: 'master'
jobs:
  deploy:
    runs-on: production
    concurrency:
      group: deploy_servers
      cancel-in-progress: true
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Check tree command installation
        id: tree_check
        continue-on-error: true
        run: which tree
      - name: Install tree command
        if: ${{ steps.tree_check.outcome == 'failure' }}
        run: sudo apt-get install tree
      - name: Display tree before cleanup
        run: tree -I venv
      - name: Display working directory before cleanup
        run: pwd
      - name: Check Docker Engine installation
        id: docker_check
        continue-on-error: true
        run: which docker
      - name: Install Docker Engine
        if: ${{ steps.docker_check.outcome == 'failure' }}
        run: >
          # Add Docker's official GPG key:
          sudo apt-get update
          sudo apt-get install ca-certificates curl
          sudo install -m 0755 -d /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
          sudo chmod a+r /etc/apt/keyrings/docker.asc

          # Add the repository to Apt sources:
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - name: Stop previous project execution
        continue-on-error: true
        run: docker container stop frontend
      - name: Cleanup project directory
        run: rm -rf ${{ github.workspace }}/*
      - name: Display tree after cleanup
        run: tree
      - name: Check out the code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.inputs.target_branch }}
      - name: Display tree after project setup
        run: tree
      - name: Build project
        run: docker build -t frontend .
      - name: Run project
        run: docker run -p 80:3000 -e OPENAI_API_KEY=$OPENAI_API_KEY frontend
